export let gameConstants = {
    // CONSTANTES PARA LA ORIENTACIÓN DE LOS BARCOS
    ORIENTATION_TO_UP_AND_DOWN: 0,
    ORIENTATION_TO_LEFT_AND_RIGHT: 1,

//CONSTANTES PARA LA DIRECCIÓN DE LOS BARCOS ORIENTADOS VERTICALMENTE
    DIRECTION_TO_UP: 0,
    DIRECTION_TO_DOWN: 1,

//CONSTANTES PARA LA DIRECCIÓN DE LOS BARCOS HORIENTADOS HORIZONTALMENTE
    DIRECTION_TO_RIGHT: 0,
    DIRECTION_TO_LEFT: 1,

}

